# -*- coding: utf-8 -*-
"""scripts.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SBusHlLU99rbDCNMogwOpQM6rqGd4hOS

# TASK 4: Word-in-Context (WiC) Disambiguation

# 1.0 Libraries
"""

import numpy as np
import pandas as pd

from google.colab import drive
drive.mount('/content/gdrive')

import json

import torch
from torch.distributions import Categorical
from transformers import AutoTokenizer, AutoModelForSequenceClassification, AutoModel, AutoModelWithLMHead

from transformers import BertForSequenceClassification, BertTokenizer

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

import time

"""# 2.0 Set up"""

train_data_path = "/content/gdrive/MyDrive/Colab Notebooks/MNLP - HW1 - task 4/Data/binary/train.jsonl"
dev_data_path = "/content/gdrive/MyDrive/Colab Notebooks/MNLP - HW1 - task 4/Data/binary/dev.jsonl"
test_data_path = "/content/gdrive/MyDrive/Colab Notebooks/MNLP - HW1 - task 4/Data/gold_truth/binary/test.jsonl"

def reformat_jsonl(input_path, output_path):
  id_seq = 0
  with open(input_path, "r") as input_file, open(output_path, "w") as output_file:
    for line in input_file:
      json_data = json.loads(line)
      reformatted_json_data = {
          "id" : id_seq,
          "lemma" : json_data["lemma"],
          "sentence1" : json_data["sentence1"],
          "sentence2" : json_data["sentence2"],
          "start1" : json_data["start1"],
          "end1" : json_data["end1"],
          "start2" : json_data["start2"],
          "end2" : json_data["end2"],
          "choices" : ["Ambiguo", "Non ambiguo"],
          "label" : json_data["label"]
      }
      json.dump(reformatted_json_data, output_file)
      output_file.write('\n')
      id_seq += 1

def read_lines_jsonl(file_path, num_lines):
  with open(file_path, 'r') as f:
    json_list = list(f)
    for line in json_list[:num_lines]:
      data = json.loads(line)
      print(data)

# italian train data
reformat_jsonl(train_data_path, "WiC-ITA_train.jsonl")
read_lines_jsonl("WiC-ITA_train.jsonl", num_lines = 10) # preview of the first 10 lines

# italian test data
reformat_jsonl(test_data_path, "WiC-ITA_test.jsonl")
read_lines_jsonl("WiC-ITA_test.jsonl", num_lines = 10) # preview of the first 10 lines

# italian dev data
reformat_jsonl(dev_data_path, "WiC-ITA_dev.jsonl")
read_lines_jsonl("WiC-ITA_dev.jsonl", num_lines = 10) # preview of the first 10 lines

"""# 3.0 Prompt formulation"""

prompts = [
    "Il significato della parola '{lemma}' risulta (Ambiguo) o (Non ambiguo) nella frase '{sentence1}' e nella frase '{sentence2}'?",
    "Confronta le frasi '{sentence1}' e '{sentence2}' per determinare se il significato della parola '{lemma}' è (Ambiguo) o (Non ambiguo)",
    "Valuta se il significato della parola '{lemma}' risulta essere (Ambiguo) o (Non Ambiguo) nella frase '{sentence1}' e nella frase '{sentence2}'."
]

print(''.join(prompt + '\n\n' for prompt in prompts), end='')

def save_prompts_jsonl(prompts, file_path):
  json_prompts = []
  for prompt in prompts:
    json_prompts.append({"prompt": prompt})

  with open(file_path, "w") as output_file:
    for json_prompt in json_prompts:
      json.dump(json_prompt, output_file)
      output_file.write("\n")

save_prompts_jsonl(prompts, "WiC-ITA_prompts.jsonl")
read_lines_jsonl("WiC-ITA_prompts.jsonl", num_lines = 3)

"""# 4.0 Performance Evaluation"""

device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
device

def evaluate_prompt(tokenizer, model, prompt, data_file):
  formatted_prompts, y_true, y_pred, score = [], [], [], []

  with open(data_file, "r") as f:
    json_data = list(f)
    for line in json_data:
      pair = json.loads(line)
      id = pair['id']
      lemma = pair['lemma']
      sentence1 = pair['sentence1']
      sentence2 =  pair['sentence2']
      start1 = pair['start1']
      end1 = pair['end1']
      start2 = pair['start2']
      end2 = pair['end2']
      choices = pair['choices']
      label = pair['label']

      formatted_prompt = prompt.format(lemma = lemma, sentence1 = sentence1, sentence2 = sentence2)
      input = tokenizer(formatted_prompt, truncation=True, return_tensors = "pt").to(device)

      with torch.no_grad():
        output = model(input["input_ids"].to(device))

      probabilities = torch.softmax(output["logits"][0], -1).tolist()
      normalized_probabilities = [prob / sum(probabilities[:2]) for prob in probabilities[:2]]
      predicted_label = np.argmax(normalized_probabilities)
      prediction_score = normalized_probabilities[predicted_label]

      formatted_prompts.append(formatted_prompt)
      y_true.append(label)
      y_pred.append(predicted_label)
      score.append(prediction_score)

    return formatted_prompts, y_true, y_pred, score


def visualize_results(results, num_results):
  choices = ["Ambiguo", "Non Ambiguo"]
  for prompt in range(len(results)):
    for n in range(num_results):
      print("Prompt: ", results[prompt][0][n])
      print("True label: ", choices[results[prompt][1][n]])
      print("Predicted label: ", choices[results[prompt][2][n]])
      print("Prediction score: ", round(results[prompt][3][n], 3))
      print("----------------------------------------------------------------")
      print(" ")

def compute_metrics(y_true, y_pred):
  accuracy = accuracy_score(y_true, y_pred)
  precision = precision_score(y_true, y_pred)
  recall = recall_score(y_true, y_pred)
  f1 = f1_score(y_true, y_pred)
  cf_matrix = confusion_matrix(y_true, y_pred)

  return accuracy, precision, recall, f1, cf_matrix


def visualize_statistics(model_name, metrics, type):
  for n in range(len(metrics)):
    print(f"{type} Statistics for the Prompt {n+1}")
    print("Prompt: ", prompts[n])

    print("Accuracy score: ", round(metrics[n][0], 3))
    print("Precision score: ", round(metrics[n][1], 3))
    print("Recall score: ", round(metrics[n][2], 3))
    print("F1-score: ", round(metrics[n][3], 3))

    # Confusion Matrix Plot
    cf_matrix = metrics[n][4]
    fig, ax = plt.subplots(figsize=(5, 3))
    sns.heatmap(cf_matrix, annot = True, fmt = '.0f')
    ax.set_title(f'{type} Confusion Matrix for Prompt {n+1} using {model_name}')
    ax.set_xlabel('Predicted Labels')
    ax.set_ylabel('True Labels')
    plt.show()

    print("Total Predictions: ", np.sum(cf_matrix))
    print("Correct Predictions: ", np.trace(cf_matrix))
    print("----------------------------------------------------------------")
    print(" ")

def visualize_statistics_table(model_name, train_metrics, test_metrics, dev_metrics, prompts):
  table = []
  for id, prompt in enumerate(prompts):
    data = {}
    for dtype, metrics in zip(['Train', 'Test', 'Dev'], [train_metrics, test_metrics, dev_metrics]):
      accuracy, f1 = metrics[id][0], metrics[id][3]
      data[f'{dtype} Accuracy {model_name}'] = round(accuracy, 3)
      data[f'{dtype} F1-score {model_name}'] = round(f1, 3)
    table.append(data)

  df_transposed = pd.DataFrame(table).transpose()
  df_transposed.columns = [f'Prompt {i+1}' for i in range(len(prompts))]

  return df_transposed

"""## mDeBERTa Base Multilingual"""

model_name = "MoritzLaurer/mDeBERTa-v3-base-xnli-multilingual-nli-2mil7"
tokenizer_mDeBERTa = AutoTokenizer.from_pretrained(model_name)
model_mDeBERTa = AutoModelForSequenceClassification.from_pretrained(model_name).to(device)

start_time = time.time()
mdeberta_train_results, mdeberta_test_results, mdeberta_dev_results = [], [], []

for prompt in prompts:
  formatted_prompt, y_true, y_pred, score = evaluate_prompt(tokenizer_mDeBERTa, model_mDeBERTa, prompt, "WiC-ITA_train.jsonl")
  mdeberta_train_results.append([formatted_prompt, y_true, y_pred, score])

  formatted_prompt, y_true, y_pred, score = evaluate_prompt(tokenizer_mDeBERTa, model_mDeBERTa,  prompt, "WiC-ITA_test.jsonl")
  mdeberta_test_results.append([formatted_prompt, y_true, y_pred, score])

  formatted_prompt, y_true, y_pred, score = evaluate_prompt(tokenizer_mDeBERTa, model_mDeBERTa, prompt, "WiC-ITA_dev.jsonl")
  mdeberta_dev_results.append([formatted_prompt, y_true, y_pred, score])

end_time = time.time()
print("Execution Time: ", (end_time - start_time)/60, "minutes")

visualize_results(mdeberta_train_results, num_results = 2) # preview of the first 2 train results for each prompt

mdeberta_train_metrics, mdeberta_test_metrics, mdeberta_dev_metrics = [], [], []

for prompt in range(len(prompts)):
  train_y_true, train_y_pred = mdeberta_train_results[prompt][1], mdeberta_train_results[prompt][2]
  accuracy, precision, recall, f1, cf_matrix = compute_metrics(train_y_true, train_y_pred)
  mdeberta_train_metrics.append([accuracy, precision, recall, f1, cf_matrix])

  test_y_true, test_y_pred = mdeberta_test_results[prompt][1], mdeberta_test_results[prompt][2]
  accuracy, precision, recall, f1, cf_matrix = compute_metrics(test_y_true, test_y_pred)
  mdeberta_test_metrics.append([accuracy, precision, recall, f1, cf_matrix])

  dev_y_true, dev_y_pred = mdeberta_dev_results[prompt][1], mdeberta_dev_results[prompt][2]
  accuracy, precision, recall, f1, cf_matrix = compute_metrics(dev_y_true, dev_y_pred)
  mdeberta_dev_metrics.append([accuracy, precision, recall, f1, cf_matrix])

"""### Statistics"""

# Train Statistics for each prompt
visualize_statistics("mDeBERTa", mdeberta_train_metrics, "Train")

# Test Statistics for each prompt
visualize_statistics("mDeBERTa", mdeberta_test_metrics, "Test")

# Dev Confusion Matrix for each prompt
visualize_statistics("mDeBERTa", mdeberta_dev_metrics, "Dev")

# Overall Statistics Table
mdeberta_table = visualize_statistics_table("mDeBERTa Base Multilingual", mdeberta_train_metrics, mdeberta_test_metrics, mdeberta_dev_metrics, prompts)
mdeberta_table