# -*- coding: utf-8 -*-
"""scripts.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-CUshfA-f-BwaxDreBRHAo8Lz9azyqfD

# TASK 26: Hypernym Discovery

# 1.0 Libraries
"""

!pip install langid
!pip install gensim
!pip install -U spacy
!python -m spacy download it_core_news_sm
!wget https://github.com/explosion/sense2vec/releases/download/v1.0.0/s2v_reddit_2015_md.tar.gz
!tar -xzvf s2v_reddit_2015_md.tar.gz
!pip install sense2vec
!pip install spacy_fastlang

import numpy as np
import pandas as pd

from google.colab import drive
drive.mount('/content/gdrive')

import re
import json
import gensim.downloader as api

import langid
from gensim.models import Word2Vec
import spacy
import spacy_fastlang

from sense2vec import Sense2Vec
import random

import torch
from transformers import RobertaTokenizer
from transformers import RobertaForMultipleChoice
from torch.distributions import Categorical
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from transformers import pipeline

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

import nltk
nltk.download('omw-1.4')
nltk.download('wordnet')
from nltk.corpus import wordnet as wn

import time
import warnings
warnings.filterwarnings('ignore')

"""# 2.0 Set up

## Load Data
"""

def load_data(data_path, gold_path):
  hypernyms_dict = {}
  with open(data_path, "r", encoding = 'utf-8') as data_file, open(gold_path, "r", encoding = 'utf-8') as gold_file:
    for data_line, gold_line in zip(data_file, gold_file):
      term_list = [term for term in data_line.split()[:-1]]
      term = " ".join(term_list)
      hypernyms = [hypernym.replace("\n", "") for hypernym in gold_line.split("\t")]
      hypernyms_dict[term] = hypernyms
  return hypernyms_dict

data_path = "/content/gdrive/MyDrive/Colab Notebooks/MNLP/Homework I - task 26/{split}/data/1B.italian.{split}.data.txt"
gold_path = "/content/gdrive/MyDrive/Colab Notebooks/MNLP/Homework I - task 26/{split}/gold/1B.italian.{split}.gold.txt"

# italian training data
train_data_path = data_path.format(split = 'training')
train_gold_path = gold_path.format(split = 'training')
train_hypernyms = load_data(train_data_path, train_gold_path)

# italian test data
test_data_path = data_path.format(split = 'test')
test_gold_path = gold_path.format(split = 'test')
test_hypernyms = load_data(test_data_path, test_gold_path)

# NLP pipeline to process italian language
nlp = spacy.load("it_core_news_sm")
nlp.add_pipe("language_detector")


def load_vocabulary(vocabulary_path):
  with open(vocabulary_path, "r", encoding = 'utf-8') as vocabulary_file:
    vocabulary = vocabulary_file.read().splitlines()
  return vocabulary


def detect_language(word):
  doc = nlp(word)
  language = doc._.language
  score = doc._.language_score
  return language, score


def clean_vocabulary(vocabulary):
  new_vocabulary = []
  for word in vocabulary:
    if word.isalpha(): # filter out numeric terms
      #language, confidence = langid.classify(word) # OLD VERSION: ineffective
      language, score = detect_language(word)
      if language == 'it' and score >= 0.5: # filter out non-italian words
        new_vocabulary.append(word)
  return new_vocabulary

"""## Load and clean Italian Vocabulary"""

# italian vocabulary
vocabulary_path = "/content/gdrive/MyDrive/Colab Notebooks/MNLP/Homework I - task 26/vocabulary/1B.italian.vocabulary.txt"
vocabulary = load_vocabulary(vocabulary_path)
print("Number of terms in the vocabulary: ", len(vocabulary), "\n")

# filtered italian vocabulary
vocabulary = clean_vocabulary(vocabulary)

# add hypernyms into vocabulary
for sublist_train, sublist_test in zip(train_hypernyms.values(), test_hypernyms.values()):
  vocabulary.extend(sublist_train)
  vocabulary.extend(sublist_test)

vocabulary = list(set(vocabulary)) # to avoid duplicates
print("Number of terms in the filtered vocabulary: ", len(vocabulary), "\n")
print("Preview of the first 20 terms in the vocabulary: ")
vocabulary[:20]

"""# 3.0 Find distractors and create entries

## First Approach: Sense2Vec
"""

# sense2vec model
s2v_model = Sense2Vec().from_disk('./s2v_old')

sense = s2v_model.get_best_sense("gatto")
s2v_model.most_similar(sense, n=5)

sense = s2v_model.get_best_sense("cane")
s2v_model.most_similar(sense, n=5)

"""**Main issues:**
*   Time constraints;
*   Presence of unrelated and non-italian distractors because the model is mainly trained using an English vocabulary.

## Second Approach: Word2Vec
"""

# word2vec model using existing vocabulary
sentences = [vocabulary]
w2v_model = Word2Vec(sentences, min_count=1)

def find_distractors(hypernym, data, term, num_distractors):
  distractors = w2v_model.wv.most_similar(hypernym, topn = 5)
  filtered_distractors = [distractor[0] for distractor in distractors if distractor[0] not in data[term]]
  return filtered_distractors[:num_distractors]

def save_jsonl(file_path, data):
  id_seq = 0
  with open(file_path, "w") as output_file:
    for term, hypernyms in data.items():
      for hypernym in hypernyms:
        distractors = find_distractors(hypernym, data, term, num_distractors = 3)
        entries = (hypernym, *distractors)
        choices = list(entries)
        random.shuffle(choices) # to create randomness
        reformatted_json_data = {
              'id' : id_seq,
              'text': term,
              'choices': choices,
              'label' : choices.index(hypernym)
        }
        json.dump(reformatted_json_data, output_file)
        output_file.write("\n")
        id_seq +=1

def read_lines_jsonl(file_path, num_lines):
  with open(file_path, 'r') as f:
    json_list = list(f)
    for line in json_list[:num_lines]:
      data = json.loads(line)
      print(data)

# train jsonl file
save_jsonl("hypernym_discovery-task26-train-data.jsonl", train_hypernyms)
read_lines_jsonl("hypernym_discovery-task26-train-data.jsonl", num_lines = 10) # preview of the first 10 lines

# test jsonl file
save_jsonl("hypernym_discovery-task26-test-data.jsonl", test_hypernyms)
read_lines_jsonl("hypernym_discovery-task26-test-data.jsonl", num_lines = 10) # preview of the first 10 lines

"""# 4.0 Prompt formulation"""

prompts = [
    "Il termine '{text}' può essere iperonimo di: \n a) {option1} \n b) {option2} \n c) {option3} \n d) {option4}",
    "Dato il termine '{text}', quale tra le seguenti parole è un suo iperonimo? \n a) {option1} \n b) {option2} \n c) {option3} \n d) {option4}",
    "Scegli l'iperonimo del termine '{text}': \n a) {option1} \n b) {option2} \n c) {option3} \n d) {option4}"
]

print(' '.join(prompt + '\n\n' for prompt in prompts), end='')

def save_prompts_jsonl(prompts, file_path):
  json_prompts = []
  for prompt in prompts:
    json_prompts.append({"prompt": prompt})

  with open(file_path, "w") as output_file:
    for json_prompt in json_prompts:
      json.dump(json_prompt, output_file)
      output_file.write("\n")

save_prompts_jsonl(prompts, "hypernym_discovery-task26-prompts.jsonl")
read_lines_jsonl("hypernym_discovery-task26-prompts.jsonl", num_lines = 3)

"""# 5.0 Prompts Evaluation"""

device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
device

def evaluate_prompt(tokenizer, model, prompt, data_file, zero_shot_classification = False):
  formatted_prompts, y_true, y_pred, score = [], [], [], []
  lines = 0

  with open(data_file, "r") as f:
    json_data = list(f)
    for line in json_data:
      pair = json.loads(line)
      id = pair['id']
      text = pair['text']
      choices = pair['choices']
      label = pair['label']

      formatted_prompt = prompt.format(text = text, option1 = choices[0], option2 = choices[1], option3 = choices[2], option4 = choices[3])
      inputs = tokenizer([formatted_prompt] * len(choices), choices,
                         padding = True, return_tensors = "pt").to(device)

      if zero_shot_classification:
        output = model(inputs, candidate_labels=choices)
        predicted_output = output['labels'][0]
        predicted_label = choices.index(predicted_output)
        prediction_score = output['scores'][0]
      else:
        labels = torch.tensor(len(choices) - 1).unsqueeze(0)
        with torch.no_grad():
          output = model(**{k: v.unsqueeze(0) for k, v in inputs.items()}, labels = labels)

        probabilities = torch.softmax(output["logits"][0], -1).tolist()
        predicted_label = np.argmax(probabilities)
        prediction_score = probabilities[predicted_label]

      formatted_prompts.append(formatted_prompt)
      y_true.append(label)
      y_pred.append(predicted_label)
      score.append(prediction_score)
      lines += 1

      # Lines limit for time constrains
      if lines == 1000:
          break

    return formatted_prompts, y_true, y_pred, score


def visualize_results(results, num_results):
  for prompt in range(len(results)):
    for n in range(num_results):
      print("Prompt: ", results[prompt][0][n])
      print("True label: ", results[prompt][1][n])
      print("Predicted label: ", results[prompt][2][n])
      print("Prediction score: ", round(results[prompt][3][n], 3))
      print("----------------------------------------------------------------")
      print(" ")

def compute_metrics(y_true, y_pred):
  accuracy = accuracy_score(y_true, y_pred)
  precision = precision_score(y_true, y_pred, average='weighted', zero_division=1)
  recall = recall_score(y_true, y_pred, average='weighted', zero_division=1)
  f1 = f1_score(y_true, y_pred, average='weighted', zero_division=1)
  cf_matrix = confusion_matrix(y_true, y_pred)
  return accuracy, precision, recall, f1, cf_matrix


def visualize_statistics(model_name, metrics, type):
  for n in range(len(metrics)):
    print(f"{type} Statistics for the Prompt {n+1}")
    print("Prompt: ", prompts[n])

    print("Accuracy score: ", round(metrics[n][0], 3))
    print("Precision score: ", round(metrics[n][1], 3))
    print("Recall score: ", round(metrics[n][2], 3))
    print("F1-score: ", round(metrics[n][3], 3))

    # Confusion Matrix Plot
    cf_matrix = metrics[n][4]
    fig, ax = plt.subplots(figsize=(5, 3))
    sns.heatmap(cf_matrix, annot = True, fmt = '.0f')
    ax.set_title(f'{type} Confusion Matrix for Prompt {n+1} using {model_name}')
    ax.set_xlabel('Predicted Labels')
    ax.set_ylabel('True Labels')
    plt.show()

    print("Total Predictions: ", np.sum(cf_matrix))
    print("Correct Predictions: ", np.trace(cf_matrix))
    print("----------------------------------------------------------------")
    print(" ")


def visualize_statistics_table(model_name, train_metrics, test_metrics, prompts):
  table = []
  for id, prompt in enumerate(prompts):
    data = {}
    for dtype, metrics in zip(['Train', 'Test'], [train_metrics, test_metrics]):
      accuracy, f1 = metrics[id][0], metrics[id][3]
      data[f'{dtype} Accuracy {model_name}'] = round(accuracy, 3)
      data[f'{dtype} F1-score {model_name}'] = round(f1, 3)
    table.append(data)

  df_transposed = pd.DataFrame(table).transpose()
  df_transposed.columns = [f'Prompt {i+1}' for i in range(len(prompts))]

  return df_transposed

"""## 5.1 RoBERTa Fine-Tuned Race model for Multiple Choices"""

model_name = "LIAMF-USP/roberta-large-finetuned-race"
roberta_tokenizer = RobertaTokenizer.from_pretrained(model_name)
roberta_model = RobertaForMultipleChoice.from_pretrained(model_name, num_labels = 4).to(device)

start_time = time.time()
roberta_train_results, roberta_test_results = [], []

for prompt in prompts:
  formatted_prompt, y_true, y_pred, score = evaluate_prompt(roberta_tokenizer, roberta_model, prompt, "hypernym_discovery-task26-train-data.jsonl")
  roberta_train_results.append([formatted_prompt, y_true, y_pred, score])

  formatted_prompt, y_true, y_pred, score = evaluate_prompt(roberta_tokenizer, roberta_model, prompt, "hypernym_discovery-task26-test-data.jsonl")
  roberta_test_results.append([formatted_prompt, y_true, y_pred, score])

end_time = time.time()
print("Execution Time: ", (end_time - start_time)/60, "minutes")

visualize_results(roberta_train_results, num_results = 2) # preview of the first 2 train results for each prompt

roberta_train_metrics, roberta_test_metrics = [], []

for prompt in range(len(prompts)):
  accuracy, precision, recall, f1, cf_matrix = compute_metrics(roberta_train_results[prompt][1], roberta_train_results[prompt][2])
  roberta_train_metrics.append([accuracy, precision, recall, f1, cf_matrix])

  accuracy, precision, recall, f1, cf_matrix = compute_metrics(roberta_test_results[prompt][1], roberta_test_results[prompt][2])
  roberta_test_metrics.append([accuracy, precision, recall, f1, cf_matrix])

"""### Statistics"""

# Train Statistics for each prompt
visualize_statistics("Roberta Fine-Tuned Race", roberta_train_metrics, "Train")

# Test Statistics for each prompt
visualize_statistics("Roberta Fine-Tuned Race", roberta_test_metrics, "Test")

# Overall Statistics Table
roberta_table = visualize_statistics_table("Roberta Fine-Tuned Race", roberta_train_metrics, roberta_test_metrics, prompts)
roberta_table

"""## 5.2 RoBERTa Large IT Multilingual Classifier for Zero Short Text Classification"""

model_name = 'Jiva/xlm-roberta-large-it-mnli'
roberta_tokenizer = AutoTokenizer.from_pretrained(model_name)
roberta_classifier = pipeline("zero-shot-classification",
                      model=model_name, batch_size = 8,
                      truncation=True, device = device)

start_time = time.time()
roberta_classifier_train_results, roberta_classifier_test_results = [], []

for prompt in prompts:
  formatted_prompt, y_true, y_pred, score = evaluate_prompt(roberta_tokenizer, roberta_classifier, prompt, "hypernym_discovery-task26-train-data.jsonl", True)
  roberta_classifier_train_results.append([formatted_prompt, y_true, y_pred, score])

  formatted_prompt, y_true, y_pred, score = evaluate_prompt(roberta_tokenizer, roberta_classifier, prompt, "hypernym_discovery-task26-test-data.jsonl", True)
  roberta_classifier_test_results.append([formatted_prompt, y_true, y_pred, score])

end_time = time.time()
print("Execution Time: ", (end_time - start_time)/60, "minutes")

visualize_results(roberta_classifier_train_results, num_results = 2) # preview of the first 2 train results for each prompt

roberta_classifier_train_metrics, roberta_classifier_test_metrics = [], []

for prompt in range(len(prompts)):
  accuracy, precision, recall, f1, cf_matrix = compute_metrics(roberta_classifier_train_results[prompt][1], roberta_classifier_train_results[prompt][2])
  roberta_classifier_train_metrics.append([accuracy, precision, recall, f1, cf_matrix])

  accuracy, precision, recall, f1, cf_matrix = compute_metrics(roberta_classifier_test_results[prompt][1], roberta_classifier_test_results[prompt][2])
  roberta_classifier_test_metrics.append([accuracy, precision, recall, f1, cf_matrix])

"""### Statistics"""

# Train Statistics for each prompt
visualize_statistics("Roberta Classifier", roberta_classifier_train_metrics, "Train")

# Train Statistics for each prompt
visualize_statistics("Roberta Classifier", roberta_classifier_test_metrics, "Test")

# Overall Statistics Table
roberta_classifier_table = visualize_statistics_table("Roberta Large IT Multilingual", roberta_classifier_train_metrics, roberta_classifier_test_metrics, prompts)
roberta_classifier_table

"""# 5.3 Comparison"""

comparison_table = pd.concat([roberta_table, roberta_classifier_table])
comparison_table